Enhance Therapy Information Screens
LoopKit/LoopKit pull request #404
Opened 2022-04-27 22:48 UTC by marionbarker

There will be a series of commits using this branch for this Pull Request.

Each commit will modify a single information screen.
A graphic will be added to the conversation for each commit showing the screen as modified.
For the first commit:
* modified BasalRatesInformationView.swift

Minor wording change to 3rd phrase.  
Addition of 4th phrase.

![BasalRatesInformationView_Update](https://user-images.githubusercontent.com/19607791/165643527-1ee7d7eb-3d42-48d6-aa1b-627fd474244d.png)

2022-04-27 23:13 UTC, marionbarker commented
Update for the CarbRatioInformationView screen.
Minor edit of 2nd phrase.
Addition of 3rd phrase.

![CarbRatioInformationView_Update](https://user-images.githubusercontent.com/19607791/165646287-ac2d9bff-f3c3-4f84-92a2-2106c2811666.png)

2022-04-28 00:09 UTC, marionbarker commented
I'm going to pause after this update and request feedback.  

There were common phrases used more than once.  I added them as new cases in `LoopKit/TherapySetting.swift` which required modification of all code that used that enum list.

I believe the repeated strings should be common - but this may not be the correct place for them to land.
I used the two strings again in the updated Correction Range Information screen shown here. The other modification was to use `insulin delivery` instead of `basal insulin` and to make Consult your health care provider disclaimer bold.


![CorrectionRangeInformationView_Update](https://user-images.githubusercontent.com/19607791/165650691-063fbf06-e9f3-440c-a670-c5217fe7e465.png)

2022-04-28 18:31 UTC, ps2 requested changes

2022-04-28 18:31 UTC, ps2 commented on LoopKit/TherapySetting.swift
> +    case addNewEntry
This enum represents different Types of settings, not different actions on those settings. It's not a general place to store translation strings, so these two new enum values are not appropriate here.

2022-04-28 18:31 UTC, ps2 commented on LoopKitUI/Views/Information Screens/BasalRatesInformationView.swift
> +            Text(LocalizedString("The schedule starts at midnight and cannot contain a single rate of 0 U/hr.", comment: "Information about basal rate scheduling"))
This is pump specific. Until we can adapt and provide pump specific advice, the lowest common denominator functionality should probably be described here.

2022-04-28 20:04 UTC, marionbarker commented
I'll put these changes into LoopDocs instead of trying to add them to the app information screens.

2022-04-28 20:04 UTC, closed without merging